language: python

cache:
  directories:
  - $HOME/nats-streaming-server

python:
  - 3.5
  - 3.6

before_install:
  - bash ./script/install_gnatsd.sh

before_script:
  - export PATH=$HOME/nats-streaming-server:$PATH
  
script:
  - ./script/test.sh

notifications:
  email: false

sudo: false
dist: trusty

# Temporary for Python 3.7
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
